baseurl = "https://streetdogg.in/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Piyush Itankar"
theme = "dream"

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
zenMode = false

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

author = "Piyush Itankar"
description = "Radom notes on experiences in life"
avatar = "img/avatar.png"
headerTitle = "〉streetdogg"
motto = "Notes from the Dog world!"

footerBottomText = "These notes are my personal views. They do not represent any of the employers/ventures I work with."

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

# email = ""

siteStartYear = 2024
favicon = "img/avatar.png"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
stickyNav = true
reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
collapseNavItems = []
noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
showPrevNextPost = true
reorderShares = ["x", "facebook", "whatsapp"]

# [params.navItems]

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"
